# Generated by Django 3.2.24 on 2024-02-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_copy_info_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_copy_info',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set Book as Returned'),)},
        ),
    ]
